version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["python", "manage.py", "run", "-h", "0.0.0.0"]
    volumes:
      - "./server:/usr/src/app"
    ports:
      - 5004:5000
    environment:
      - RABBIT_USER=test
      - RABBIT_PASS=test
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    command: ["python", "main.py"]
    volumes:
      - "./worker:/usr/src/app"
    environment:
      - RABBIT_USER=test
      - RABBIT_PASS=test
      - RABBIT_HOST=rabbitmq
    depends_on:
      - api
      - rabbitmq

  winner:
    build:
      context: ./winner
      dockerfile: Dockerfile
    command:
      [
        "gunicorn",
        "project.wsgi:app",
        "-k",
        "geventwebsocket.gunicorn.workers.GeventWebSocketWorker",
        "-w",
        "1",
        "--bind",
        "0.0.0.0:5000",
      ]
    ports:
      - 5005:5000
    volumes:
      - "./winner:/usr/src/app"
    environment:
      - SOCKETIO_MESSAGE_QUEUE=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  rabbitmq:
    image: rabbitmq:3.10.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - 5672:5672
      - 15672:15672

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "./client:/app"
    depends_on:
      - api
      - winner
  redis:
    image: redis:7.0.2-alpine
